# Generated by Django 5.0.3 on 2024-04-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronos", "0002_alter_sentiment_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="recommended_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
