# Generated by Django 5.0.3 on 2024-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronos", "0004_product_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
