# Generated by Django 5.0.3 on 2024-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronos", "0006_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
