# Generated by Django 5.0.3 on 2024-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronos", "0007_alter_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_count",
            field=models.IntegerField(default=0),
        ),
    ]
