# Generated by Django 5.0.3 on 2024-04-21 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kronos", "0008_product_sale_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sale_count",
        ),
    ]
